# Generated by Django 4.1.7 on 2023-05-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_events_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeUser',
        ),
    ]
